# Generated by Django 5.2.2 on 2025-06-09 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(max_length=100)),
                ('proveedor_Pago', models.CharField(max_length=100)),
                ('fecha_Procesamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
