# Generated by Django 4.2.11 on 2025-06-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donante', '0001_initial'),
        ('transaccion', '0002_transaccion_onante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='onante',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='donante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donante.donante'),
        ),
    ]
