# Generated by Django 5.2.2 on 2025-06-15 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donantes', to='campania.campania')),
            ],
            options={
                'verbose_name_plural': 'Donantes',
                'ordering': ['nombre'],
            },
        ),
    ]
