# Generated by Django 5.2.2 on 2025-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ong',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'ONGs'},
        ),
        migrations.RemoveField(
            model_name='ong',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ong',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ong',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='mision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
