# Generated by Django 5.2 on 2025-06-09 04:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto mínimo: $1', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('comprobante', models.FileField(blank=True, help_text='Formatos: PDF, JPEG, PNG', null=True, upload_to='comprobantes/')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje opcional')),
            ],
            options={
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
